export { default as img123 } from './src/icons/123.png'
export { ReactComponent as Icon24px } from './src/icons/24px.svg'
export { ReactComponent as IconAbc } from './src/icons/abc.svg'
export { ReactComponent as IconAce } from './src/icons/ace.svg'
export { ReactComponent as IconLogokeku24px } from './src/icons/logo/keku/24px.svg'
export { ReactComponent as IconLogologotip } from './src/icons/logo/logotip.svg'
export { ReactComponent as IconSax } from './src/icons/sax.svg'
export { ReactComponent as IconSda } from './src/icons/sda.svg'